{"uuid": "6301823a-80e3-4f93-8c41-a74e43addc8f", "children": ["cad19a5a-c27a-4bda-97b7-a2e0ecbec7b7"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Dror\\Desktop\\Automation\\PythonAutomationFramework_1-master\\conftest.py\", line 20, in test_setup\n    driver.maximize_window()\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n    httplib_response = self._make_request(\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n    httplib_response = conn.getresponse()\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\http\\client.py\", line 1332, in getresponse\n    response.begin()\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\http\\client.py\", line 303, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\http\\client.py\", line 264, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\Dror\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1593971005315, "stop": 1593971016107}], "start": 1593971005315, "stop": 1593971016538}