{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: value_exists() missing 1 required positional argument: 'value'", "trace": "self = <login_test.TestLogin object at 0x03D2E898>\n\n    def test_login(self):\n        try:\n    \n            driver = self.driver\n            driver.get(utils.URL)\n    \n            login = LoginPage(driver)\n            homepage= HomePage(driver)\n            eventspage = EventsPage(driver)\n    \n            login.enter_username(utils.USERNAME)\n            login.enter_instance(utils.INSTANCE)\n            login.enter_password(utils.PASSWORD)\n            login.click_login()\n            homepage.navigate_events_screen()\n            eventspage.search_value(\"NewUser\")\n            time.sleep(5)\n>           eventspage.value_exists(\"NewUser\")\nE           TypeError: value_exists() missing 1 required positional argument: 'value'\n\ntests\\login_test.py:34: TypeError"}, "attachments": [{"name": "test_login_05-07-2020_19-48-21", "source": "15b22adc-f7f0-40c0-b6f3-40f62382cb2d-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "6852bb3e-61f4-46b7-863d-319c989ccd1a-attachment.txt", "type": "text/plain"}], "start": 1593967684643, "stop": 1593967702181, "uuid": "13a78ecd-9a91-4121-a3eb-07554fcbec7b", "historyId": "8a9dfa4f406383cd388e6699ea6b6a72", "testCaseId": "2ce0d2b159a1b134adc13e328bfd71c0", "fullName": "tests.login_test.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "20148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}