{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: value_exists() missing 1 required positional argument: 'value'", "trace": "self = <login_test.TestLogin object at 0x03C807D8>\n\n    def test_login(self):\n        try:\n    \n            driver = self.driver\n            driver.get(utils.URL)\n    \n            login = LoginPage(driver)\n            homepage= HomePage(driver)\n            eventspage = EventsPage(driver)\n    \n            login.enter_username(utils.USERNAME)\n            login.enter_instance(utils.INSTANCE)\n            login.enter_password(utils.PASSWORD)\n            login.click_login()\n            homepage.navigate_events_screen()\n            # eventspage.search_value(\"NewUser\")\n            # time.sleep(5)\n            # eventspage.value_exists(\"NewUser\")\n            # time.sleep(5)\n            eventspage.search_value(\"Purchase\")\n            time.sleep(5)\n>           eventspage.value_exists()\nE           TypeError: value_exists() missing 1 required positional argument: 'value'\n\ntests\\login_test.py:38: TypeError"}, "attachments": [{"name": "test_login_05-07-2020_20-50-29", "source": "8981230f-2414-4cb4-ae19-8e508e78e986-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "873b5030-b2e3-4e50-a3f2-9d37b1ce7120-attachment.txt", "type": "text/plain"}], "start": 1593971409728, "stop": 1593971430506, "uuid": "22cd45ac-559e-462a-a59f-e29e3e6f4f34", "historyId": "8a9dfa4f406383cd388e6699ea6b6a72", "testCaseId": "2ce0d2b159a1b134adc13e328bfd71c0", "fullName": "tests.login_test.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "19152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}