{"name": "test_login", "status": "broken", "statusDetails": {"message": "NameError: name 'username' is not defined", "trace": "self = <login_test.TestLogin object at 0x0411F6D0>\n\n    def test_login(self):\n    \n            driver = self.driver\n            driver.get(utils.URL)\n    \n            login = LoginPage(driver)\n            login.enter_username(utils.USERNAME)\n>           login.enter_instance(utils.INSTANCE)\n\ntests\\login_test.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.LoginPage.flows.LoginPage object at 0x047E00A0>, instace = 'demo'\n\n    def enter_instance(self,instace):\n        self.driver.find_element(*Main.instance_textbox).clear()\n>       self.driver.find_element(*Main.instance_textbox).send_keys(username)\nE       NameError: name 'username' is not defined\n\npages\\LoginPage\\flows.py:21: NameError"}, "start": 1593964335348, "stop": 1593964340238, "uuid": "7a91ffb7-ce41-4839-a887-a750668faaa8", "historyId": "8a9dfa4f406383cd388e6699ea6b6a72", "testCaseId": "2ce0d2b159a1b134adc13e328bfd71c0", "fullName": "tests.login_test.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}