{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: value_exists() missing 1 required positional argument: 'value'", "trace": "self = <login_test.TestLogin object at 0x03CDA3E8>\n\n    def test_login(self):\n        try:\n    \n            driver = self.driver\n            driver.get(utils.URL)\n    \n            login = LoginPage(driver)\n            homepage= HomePage(driver)\n            eventspage = EventsPage(driver)\n    \n            login.enter_username(utils.USERNAME)\n            login.enter_instance(utils.INSTANCE)\n            login.enter_password(utils.PASSWORD)\n            login.click_login()\n            homepage.navigate_events_screen()\n            eventspage.search_value(\"NewUser\")\n            time.sleep(5)\n>           eventspage.value_exists(\"NewUser\")\nE           TypeError: value_exists() missing 1 required positional argument: 'value'\n\ntests\\login_test.py:34: TypeError"}, "attachments": [{"name": "test_login_05-07-2020_19-46-41", "source": "b5c8916d-ebb4-434a-b146-c3bb6fdec530-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "12cd021b-168c-458c-8ccb-8eae2fb2d142-attachment.txt", "type": "text/plain"}], "start": 1593967584590, "stop": 1593967602691, "uuid": "bbbdc730-0e02-4fbf-83e5-351f18338a28", "historyId": "8a9dfa4f406383cd388e6699ea6b6a72", "testCaseId": "2ce0d2b159a1b134adc13e328bfd71c0", "fullName": "tests.login_test.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('test_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-BFIIM5B"}, {"name": "thread", "value": "2660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}